package com.flyonz.ceritaria.studio.core.database.videojob

import com.flyonz.ceritaria.studio.core.media.VideoEncodingStatus
import com.flyonz.ceritaria.studio.core.media.VideoMetadata
import com.flyonz.ceritaria.studio.core.upload.VideoUploadStatus
import java.time.Instant

fun VideoJobEntity.toDomain(): VideoJob = VideoJob(
    jobId = jobId,
    episodeId = episodeId,
    sourceUri = sourceUri,
    sourceFingerprint = sourceFingerprint,
    sourceMetadata = VideoMetadata(
        containerMimeType = sourceContainerMimeType,
        sizeBytes = sourceSizeBytes,
        durationMs = sourceDurationMs,
        width = sourceWidth,
        height = sourceHeight,
        rotationDegrees = sourceRotationDegrees,
        frameRate = sourceFrameRate,
        videoMimeType = sourceVideoMimeType,
        audioMimeType = sourceAudioMimeType,
        audioBitrate = sourceAudioBitrate,
        audioSampleRate = sourceAudioSampleRate,
        hasVideo = sourceHasVideo,
        hasAudio = sourceHasAudio,
    ),
    needsEncoding = needsEncoding,
    encodedLocalUri = encodedLocalUri,
    encodingStatus = VideoEncodingStatus.valueOf(encodingStatus),
    encodingProgress = encodingProgress,
    uploadStatus = VideoUploadStatus.valueOf(uploadStatus),
    uploadedBytes = uploadedBytes,
    totalBytes = totalBytes,
    uploadSessionId = uploadSessionId,
    multipartState = multipartState,
    remoteAssetId = remoteAssetId,
    lastErrorCode = lastErrorCode,
    createdAt = Instant.ofEpochMilli(createdAtEpochMs),
    updatedAt = Instant.ofEpochMilli(updatedAtEpochMs),
)

fun VideoJob.toEntity(): VideoJobEntity = VideoJobEntity(
    jobId = jobId,
    episodeId = episodeId,
    sourceUri = sourceUri,
    sourceFingerprint = sourceFingerprint,
    sourceContainerMimeType = sourceMetadata.containerMimeType,
    sourceSizeBytes = sourceMetadata.sizeBytes,
    sourceDurationMs = sourceMetadata.durationMs,
    sourceWidth = sourceMetadata.width,
    sourceHeight = sourceMetadata.height,
    sourceRotationDegrees = sourceMetadata.rotationDegrees,
    sourceFrameRate = sourceMetadata.frameRate,
    sourceVideoMimeType = sourceMetadata.videoMimeType,
    sourceAudioMimeType = sourceMetadata.audioMimeType,
    sourceAudioBitrate = sourceMetadata.audioBitrate,
    sourceAudioSampleRate = sourceMetadata.audioSampleRate,
    sourceHasVideo = sourceMetadata.hasVideo,
    sourceHasAudio = sourceMetadata.hasAudio,
    needsEncoding = needsEncoding,
    encodedLocalUri = encodedLocalUri,
    encodingStatus = encodingStatus.name,
    encodingProgress = encodingProgress,
    uploadStatus = uploadStatus.name,
    uploadedBytes = uploadedBytes,
    totalBytes = totalBytes,
    uploadSessionId = uploadSessionId,
    multipartState = multipartState,
    remoteAssetId = remoteAssetId,
    lastErrorCode = lastErrorCode,
    createdAtEpochMs = createdAt.toEpochMilli(),
    updatedAtEpochMs = updatedAt.toEpochMilli(),
)
